<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Productos BM.aspx.cs" Inherits="Vistas.Productos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>

    <div class="container">
       
        <form id="form1" runat="server" class="mb-3">

            <div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink1" class="nav-link" runat="server" NavigateUrl="~/Pagina Principal Admin.aspx">Pagina principal</asp:HyperLink>
                </li>
                <li class="nav-item dropdown">
                    <asp:HyperLink ID="HyperLink7" class="nav-link" runat="server" NavigateUrl="~/Productos BM.aspx">Productos</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink8" class="nav-link" runat="server" NavigateUrl="~/Proveedores.aspx">Proveedores</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink9" class="nav-link" runat="server" NavigateUrl="~/Usuarios.aspx">Usuarios</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink10" class="nav-link" runat="server" NavigateUrl="~/Ventas.aspx">Ventas</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink11" class="nav-link" runat="server" NavigateUrl="~/Registrar Admin.aspx">Registrar Administrador</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink12" class="nav-link" runat="server" NavigateUrl="~/Provincias.aspx">Provincias</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink2" class="nav-link" runat="server" NavigateUrl="~/Tipos de Producto.aspx">Tipos de Producto</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:Label ID="lblNombre" class="nav-link" runat="server" Text=""></asp:Label>
                </li>
                <li class="nav-item">
                    <asp:LinkButton ID="LinkButton1" class="nav-link" runat="server" OnClick="LinkButton1_Click">Cerrar Session</asp:LinkButton>
                </li>

            </ul>
        </div>
            <div class="row">
                <asp:Label ID="lblProductos" runat="server" Font-Bold="True" Font-Size="XX-Large" Font-Underline="True" Text="Productos"></asp:Label>
            </div>
            <br />
            <div class="row">
                <div class="col-2">
                    <asp:Label ID="Label1" class="alert alert-light " role="alert" runat="server">Buscar por id</asp:Label></div>
                <div class="col-4">
                    <asp:TextBox ID="tbIdProducto" class="form-control form-control-sm" runat="server" OnTextChanged="tbIdProducto_TextChanged" TextMode="Number"></asp:TextBox></div>
                <div class="col-2">
                    <asp:Button ID="btnFiltrar" class="btn btn-primary" runat="server" OnClick="btnFiltrar_Click" Text="Buscar" /></div>
            </div>
            <br />
            <div class="row">
                <div class="col-2">
                    <asp:Label ID="Label2" class="alert alert-light " role="alert" runat="server">Buscar por nombre</asp:Label></div>
                <div class="col-4">
                    <asp:TextBox ID="tbBuscarNombre" class="form-control form-control-sm" runat="server" OnTextChanged="tbIdProducto_TextChanged"></asp:TextBox></div>
                <div class="col-2">
                    <asp:Button ID="btnBuscar2" class="btn btn-primary" runat="server" OnClick="btnBuscar2_Click" Text="Buscar" /></div>
            </div>

            <br />
            <br />
            <asp:GridView ID="grvProductos" class="table table-striped table-hover" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnPageIndexChanging="grvProductos_PageIndexChanging" OnRowCancelingEdit="grvProductos_RowCancelingEdit" OnRowDeleting="grvProductos_RowDeleting" OnRowEditing="grvProductos_RowEditing" OnRowUpdating="grvProductos_RowUpdating" PageSize="5">
                
                <Columns >
                    <asp:TemplateField HeaderText="ID PRODUCTO">
                        <ItemTemplate>
                            <asp:Label ID="lbl_It_IdProducto" runat="server" Text='<%# Bind("Id_Producto_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="ID PROVEEDOR">
                        <EditItemTemplate>
                            <asp:TextBox ID="tb_Eit_IdProveedor" runat="server" Text='<%# Bind("Id_Proveedor_P") %>' TextMode="Number"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_It_IdProveedor" runat="server" Text='<%# Bind("Id_Proveedor_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="DESCRIPCION">
                        <EditItemTemplate>
                            <asp:TextBox ID="tb_Eit_Descripcion" runat="server" Text='<%# Bind("Descripcion_Producto_P") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_It_Descripcion" runat="server" Text='<%# Bind("Descripcion_Producto_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="PRECIO UNITARIO">
                        <EditItemTemplate>
                            <asp:TextBox ID="tb_Eit_PrecioUnitario" runat="server" Text='<%# Bind("Precio_Unitario_P") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_It_PrecioUnitario" runat="server" Text='<%# Bind("Precio_Unitario_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="NOMBRE PRODUCTO">
                        <EditItemTemplate>
                            <asp:TextBox ID="tb_Eit_NombreProducto" runat="server" MaxLength="20" Text='<%# Bind("Nombre_Producto_P") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_It_NombreProducto" runat="server" Text='<%# Bind("Nombre_Producto_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="ID TIPO PRODUCTO">
                        <EditItemTemplate>
                            <asp:TextBox ID="tb_Eit_IdTipoProducto" runat="server" Text='<%# Bind("Id_Tipo_Producto_P") %>' TextMode="Number"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_It_IdTipoProducto" runat="server" Text='<%# Bind("Id_Tipo_Producto_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="URL IMAGEN">
                        <EditItemTemplate>
                            <asp:TextBox ID="tb_Eit_UrlImagen" runat="server" MaxLength="25" Text='<%# Bind("Imagen_Producto_P") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_It_UrlImagen" runat="server" Text='<%# Bind("Imagen_Producto_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="STOCK">
                        <EditItemTemplate>
                            <asp:TextBox ID="tb_Eit_Stock" runat="server" Text='<%# Bind("Stock_Producto_P") %>' TextMode="Number"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Stock" runat="server" Text='<%# Bind("Stock_Producto_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="ESTADO">
                        <EditItemTemplate>
                            <asp:CheckBox ID="chb_Eit_Estado" runat="server" Checked='<%# Bind("Estado_P") %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_It_Estado" runat="server" Text='<%# Bind("Estado_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <asp:Label ID="lblMensaje" runat="server"></asp:Label>
            <br />
            <asp:HyperLink ID="hlAgregarProducto" runat="server" NavigateUrl="~/Agregar productos.aspx">Agregar producto</asp:HyperLink>
    </form>
        
  </div>
    
</body>
</html>
