<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Productos seleccionados.aspx.cs" Inherits="Vistas.Productos_seleccionados" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
    <div class="container">
    <form id="form1" runat="server">
        <div>
            <div>
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <asp:HyperLink ID="HyperLink" class="nav-link" runat="server" NavigateUrl="~/Pagina Principal Sesion Iniciada.aspx">Pagina principal</asp:HyperLink>
                    </li>
                    <li class="nav-item">
                        <asp:HyperLink ID="Editar_Perfil" class="nav-link" runat="server" NavigateUrl="~/Modificar Datos.aspx">Editar Perfil</asp:HyperLink>
                    </li>
                    <li class="nav-item align-center">
                        <asp:Label ID="lblNombre" class="alert alert-info " runat="server" Text=""></asp:Label>
                    </li>
                    <li class="nav-item">
                        <asp:LinkButton ID="LinkButton1" class="nav-link" runat="server" OnClick="LinkButton1_Click">Cerrar Session</asp:LinkButton>
                    </li>
                </ul>
            </div>
            <asp:Label ID="lblCarrito" runat="server" Font-Bold="True" Font-Size="XX-Large" Font-Underline="True" Text="Carrito"></asp:Label>
           
            <br />
            <asp:GridView ID="grvCarrito" class="table table-striped table-hover" runat="server" AutoGenerateDeleteButton="True"  AutoGenerateColumns="False" OnRowDeleting="grvCarrito_RowDeleting">
                <Columns>
                    <asp:BoundField DataField="ID Producto" HeaderText="ID" />
                    <asp:BoundField DataField="Nombre Producto" HeaderText="Nombre" />
                    <asp:BoundField DataField="Descripcion Producto" HeaderText="Descripcion" />
                    <asp:BoundField DataField="Precio unitario" HeaderText="Precio Unitario" />
                    <asp:BoundField DataField="Stock" HeaderText="Stock" />
                    <asp:TemplateField HeaderText="Cantidad">
                        <ItemTemplate>
                            <asp:TextBox ID="txtCantidad" runat="server">1</asp:TextBox>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="Subtotal" HeaderText="Subtotal" />
                </Columns>
            </asp:GridView>
            <asp:Label ID="lblCarritoVacio" runat="server" Font-Bold="True" Font-Size="XX-Large"></asp:Label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Label ID="lblMontoTotal" runat="server"></asp:Label>
            <br />
            <asp:Button ID="btnFinalizar" class="btn btn-primary" runat="server" Text="Finalizar compra" Width="142px" OnClick="btnFinalizar_Click" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnActualizar" class="btn btn-primary" runat="server" OnClick="btnActualizar_Click" Text="Actualizar" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:Button ID="btnConfirmar" runat="server" OnClick="btnConfirmar_Click" EnableViewState="False" Height="30px" Text="Confirmar compra" Visible="False" Width="150px" />
            &nbsp;&nbsp;<asp:Button ID="btnCancelar" runat="server" Height="30px" OnClick="btnCancelar_Click" Text="Cancelar" Visible="False" Width="150px" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Label ID="lblError" runat="server"></asp:Label>
            <br />
            <asp:Label ID="lblCompraFinalizada" runat="server"></asp:Label>
        </div>
    </form>
        </div>
</body>
</html>
