<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Provincias.aspx.cs" Inherits="Vistas.Provincias" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" />

</head>
<body>
    <div class="container">


        <form id="form1" runat="server" class="mb-3">

            <div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink1" class="nav-link" runat="server" NavigateUrl="~/Pagina Principal Admin.aspx">Pagina principal</asp:HyperLink>
                </li>
                <li class="nav-item dropdown">
                    <asp:HyperLink ID="HyperLink7" class="nav-link" runat="server" NavigateUrl="~/Productos BM.aspx">Productos</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink8" class="nav-link" runat="server" NavigateUrl="~/Proveedores.aspx">Proveedores</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink9" class="nav-link" runat="server" NavigateUrl="~/Usuarios.aspx">Usuarios</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink10" class="nav-link" runat="server" NavigateUrl="~/Ventas.aspx">Ventas</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink11" class="nav-link" runat="server" NavigateUrl="~/Registrar Admin.aspx">Registrar Administrador</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink12" class="nav-link" runat="server" NavigateUrl="~/Provincias.aspx">Provincias</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink2" class="nav-link" runat="server" NavigateUrl="~/Tipos de Producto.aspx">Tipos de Producto</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:Label ID="lblNombre" class="nav-link" runat="server" Text=""></asp:Label>
                </li>
                <li class="nav-item">
                    <asp:LinkButton ID="LinkButton1" class="nav-link" runat="server" OnClick="LinkButton1_Click">Cerrar Session</asp:LinkButton>
                </li>

            </ul>
        </div>

            <div>
                <div>
                    <div class="row">
                        <asp:Label ID="lblProductos" runat="server" Font-Bold="True" Font-Size="XX-Large" Font-Underline="True" Text="Provincias"></asp:Label>
                    </div>
                    <br />

                    <asp:GridView ID="grdProvincias" class="table table-striped table-hover" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="grdProvincia_RowDeleting" OnRowCancelingEdit="grdProvincias_RowCancelingEdit" OnRowEditing="grdProvincias_RowEditing" OnRowUpdating="grdProvincias_RowUpdating" AllowPaging="True" OnPageIndexChanging="grdProvincias_PageIndexChanging" PageSize="5">
                        <Columns>
                            <asp:TemplateField HeaderText="IdProvincia">
                                <ItemTemplate>
                                    <asp:Label ID="lbl_it_IdProvincia" runat="server" Text='<%# Bind("Id_Provincia_Pr") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Provincia">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txt_ed_Provincia" runat="server" Text='<%# Bind("Descripcion_Provincia_Pr") %>' Height="20px"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblProvincia" runat="server" Text='<%# Bind("Descripcion_Provincia_Pr") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Estado">
                                <EditItemTemplate>
                                    <asp:CheckBox ID="chb_Eit_Estado" runat="server" Checked='<%# Bind("Estado_Provincia_Pr") %>' />
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lbl_It_Estado" runat="server" Text='<%# Bind("Estado_Provincia_Pr") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                    <asp:Label ID="lblMensaje" runat="server"></asp:Label>
                    <br />
                    <span class="auto-style2"><strong>Agregar Provincia<br />
                    </strong>
                        <br />
                        Provincia </span>
                    <div class="col-3">
                    <asp:TextBox ID="txtProvincia" class="form-control form-control-sm" runat="server" OnTextChanged="txtProvincia_TextChanged" MaxLength="20"></asp:TextBox>
                    </div>
                    <br />
                    <asp:Button ID="btnAgregar" class="btn btn-primary" runat="server" OnClick="btnAgregar_Click" Text="Agregar" />
                </div>
            </div>
        </form>
    </div>
</body>
</html>
