<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Tipos de Producto.aspx.cs" Inherits="Vistas.Tipos_de_Producto" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
    <div class="container">
    <form id="form2" runat="server" class="mb-3">
        <div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink1" class="nav-link" runat="server" NavigateUrl="~/Pagina Principal Admin.aspx">Pagina principal</asp:HyperLink>
                </li>
                <li class="nav-item dropdown">
                    <asp:HyperLink ID="HyperLink7" class="nav-link" runat="server" NavigateUrl="~/Productos BM.aspx">Productos</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink8" class="nav-link" runat="server" NavigateUrl="~/Proveedores.aspx">Proveedores</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink9" class="nav-link" runat="server" NavigateUrl="~/Usuarios.aspx">Usuarios</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink10" class="nav-link" runat="server" NavigateUrl="~/Ventas.aspx">Ventas</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink11" class="nav-link" runat="server" NavigateUrl="~/Registrar Admin.aspx">Registrar Administrador</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink12" class="nav-link" runat="server" NavigateUrl="~/Provincias.aspx">Provincias</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:HyperLink ID="HyperLink2" class="nav-link" runat="server" NavigateUrl="~/Tipos de Producto.aspx">Tipos de Producto</asp:HyperLink>
                </li>
                <li class="nav-item">
                    <asp:Label ID="lblNombre" class="nav-link" runat="server" Text=""></asp:Label>
                </li>
                <li class="nav-item">
                    <asp:LinkButton ID="LinkButton1" class="nav-link" runat="server" OnClick="LinkButton1_Click">Cerrar Session</asp:LinkButton>
                </li>

            </ul>
        </div>
        <div>
            <div class="row">
            <br />
            <asp:Label ID="lblTitulo" runat="server" Font-Bold="True" Font-Size="XX-Large" Font-Underline="True" Text="Tipos de Productos"></asp:Label>
            </div>
            <br />
            <asp:GridView ID="grdTipoProducto" class="table table-striped table-hover" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnPageIndexChanging="grdTipoProducto_PageIndexChanging" OnRowCancelingEdit="grdTipoProducto_RowCancelingEdit" OnRowDeleting="grdTipoProducto_RowDeleting" OnRowEditing="grdTipoProducto_RowEditing" OnRowUpdating="grdTipoProducto_RowUpdating" AllowPaging="True" PageSize="5">
                <Columns>
                    <asp:TemplateField HeaderText="Id Tipo De Producto">
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_IdTipo" runat="server" Text='<%# Bind("Id_Tipo_Producto_T") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Tipo de Producto">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_ed_TipoProducto" runat="server" Text='<%# Bind("Descripcion_Tipo_Producto_T") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblTipoDeProducto" runat="server" Text='<%# Bind("Descripcion_Tipo_Producto_T") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Estado">
                        <EditItemTemplate>
                            <asp:CheckBox ID="chb_Eit_Estado" runat="server" Checked='<%# Bind("Estado_Tipo_Producto_T") %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_It_Estado" runat="server" Text='<%# Bind("Estado_Tipo_Producto_T") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <br />
            <asp:Label ID="lblMensaje" runat="server"></asp:Label>
            <br />
            <div>
                <span class="auto-style2"><strong>Agregar Tipo de Producto<br />
                </strong></span>
                <br />

                <div class="col-3">
                <asp:TextBox ID="txtTipoDeProducto" class="form-control form-control-sm" runat="server" OnTextChanged="txtTipoDeProducto_TextChanged"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtTipoDeProducto" ValidationGroup="grupo1">debe ingresar un tipo</asp:RequiredFieldValidator>
                </div>
                <br />
                <asp:Button ID="btnAgregar" class="btn btn-primary" runat="server" OnClick="btnAgregar_Click" Text="Agregar" ValidationGroup="grupo1" />
                &nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Label ID="lblAgregado" runat="server"></asp:Label>
            </div>
           
        </div>
    </form>
        </div>
</body>
</html>
